### ISSUE TITLE
Cannot install rulex on a debian11 system

### ISSUE THREAD

**Issue by sevapopov2** [poretsky/rulex#1]
Hello,
I try to install ru_tts and rulex on the debian11 system.
Unfortunately, I cannot find any instructions on how to install ru_tts, but I will describe the problem in it's own repo.
Here's what issue I have while compiling rulex.
make -e -C src all
make[1]: вход в каталог «/home/seva/AppsForCompiling/rulex/src»
libtool --mode=compile gcc -c -Wall -O2 -D_REENTRANT coder.c
make[1]: libtool: нет такого файла или каталога.
make[1]: *** [Makefile:45: coder.lo] Ошибка 127
make[1]: выход из каталога «/home/seva/AppsForCompiling/rulex/src»
make: *** [Makefile:15: lexholder] Ошибка 2
However, libtool library is installed.
Before that I had an issue with rulex.db.h file couldn't be found, but I installed a libdb-dev library and it was solved.
How can I continue the installation process of rulex?
Any help will be appreciated.
Thank you!

**Comment by poretsky** [comment]
Unfortunately, I don't see any complaint. There are messages about
entering and leaving directory and compilation command. Nothing to guess
the cause of failure.

Did you try simply to invoke make without arguments in the root of
project? What the reason the "-e" switch is used for? Anyway, variable
"LANG" is set inside Makefile during the build process. And it is
necessary to have koi8-r locale generated in the system.

**Comment by sevapopov2** [comment]
> Unfortunately, I don't see any complaint. There are messages about entering and leaving directory and compilation command. Nothing to guess the cause of failure. Did you try simply to invoke make without arguments in the root of project? What the reason the "-e" switch is used for? Anyway, variable "LANG" is set inside Makefile during the build process. And it is necessary to have koi8-r locale generated in the system.

**Comment by sevapopov2** [comment]
Hello,
Thank you for your reply!
As far as envoking make command:
I simply type
make
in the project root directory without any flags.
Make -e -c src/all is what the output always types after enwoking it.
As far as KOI8-R locale, thank you for the information, I didn't know it should be separately generated.
I generated it, run the command make in the root folder of the project again and it still gives the same output.
Thank you!
P.S. Closed the issue first by the accident.

**Comment by poretsky** [comment]
Try the following:

sudo apt install libtool-bin

**Comment by sevapopov2** [comment]
Thank you, it worked!
I installed the library you suggested and the compilation went well with installing without any errors.
