### ISSUE TITLE
should these erroneous words be in the rulex?

### ISSUE THREAD

**Issue by kirill-jjj** [poretsky/rulex#3]
from explicit.dict
видиозахвата видиозахва+та
видиопамяти видиопа+мяти
вилазь вила+зь
from implicit.dict
видиокартам видиока+ртам
видиоодаптер видиоода+птэр
видиотеки видиоте+ки
видиофайлов видиофа+йлов
аудеокассетам аудеокассе+там
I have found the most obvious so far, but there is still enough of such good there.

**Comment by kirill-jjj** [comment]
and yet, the stress is not correctly placed here for the literary Russian language.
мусоропровод мусоропро+вод
must be
мусоропровод мусоропрово+д
the evidence is here
https://kakpishem.ru/udarenie-v-slovah/kak-pravilno-govorit-musoroprovod-ili-musoroprovod.html

**Comment by kirill-jjj** [comment]
and the coolest thing
эспиранто эспира+нто

**Comment by kirill-jjj** [comment]
преобрести преобрести+

**Comment by poretsky** [comment]
Such words are just redundancies originating from the old time when I
used various text to grow dictionary. There is no much harm of them in
general, but on the other hand, yes, there is no reason to keep them in
the dictionary.

**Comment by poretsky** [comment]
Fixed via #4
